// SPDX-License-Identifier: MIT 
pragma solidity >=0.8.0;

// NOTE: This file is autogenerated via `mud codegen-libdeploy` from `deploy.json`. Do not edit manually.

// Foundry
import { DSTest } from "ds-test/test.sol";
import { console } from "forge-std/console.sol";

// Solecs 
import { World } from "solecs/World.sol";
import { Component } from "solecs/Component.sol";
import { getAddressById } from "solecs/utils.sol";
import { IUint256Component } from "solecs/interfaces/IUint256Component.sol";
import { ISystem } from "solecs/interfaces/ISystem.sol";

// Components (requires 'components=...' remapping in project's remappings.txt)
import { IndexerComponent, ID as IndexerComponentID } from "components/IndexerComponent.sol";
import { PositionComponent, ID as PositionComponentID } from "components/PositionComponent.sol";
import { ColorComponent, ID as ColorComponentID } from "components/ColorComponent.sol";

// Systems (requires 'systems=...' remapping in project's remappings.txt)
import { InitSystem, ID as InitSystemID } from "systems/InitSystem.sol";
import { PaintSystem, ID as PaintSystemID } from "systems/PaintSystem.sol";
import { PaintRectSystem, ID as PaintRectSystemID } from "systems/PaintRectSystem.sol";

struct DeployResult {
  World world;
  address deployer;
}

library LibDeploy {
  function deploy(
    address _deployer,
    address _world,
    bool _reuseComponents
  ) internal returns (DeployResult memory result) {
    result.deployer = _deployer;

    // ------------------------
    // Deploy 
    // ------------------------

    // Deploy world
    result.world = _world == address(0) ? new World() : World(_world);
    if (_world == address(0)) result.world.init(); // Init if it's a fresh world

    // Deploy components
    if (!_reuseComponents) {
      Component comp;

      console.log("Deploying IndexerComponent");
      comp = new IndexerComponent(address(result.world));
      console.log(address(comp));

      console.log("Deploying PositionComponent");
      comp = new PositionComponent(address(result.world));
      console.log(address(comp));

      console.log("Deploying ColorComponent");
      comp = new ColorComponent(address(result.world));
      console.log(address(comp));
    } 
    
    // Deploy systems 
    deploySystems(address(result.world), true);
  }
  
  function authorizeWriter(
    IUint256Component components,
    uint256 componentId,
    address writer
  ) internal {
    Component(getAddressById(components, componentId)).authorizeWriter(writer);
  }
  
  /**
   * Deploy systems to the given world.
   * If `init` flag is set, systems with `initialize` setting in `deploy.json` will be executed.
   */
  function deploySystems(
    address _world,
    bool init
  ) internal {
    World world = World(_world);
    // Deploy systems
    ISystem system; 
    IUint256Component components = world.components();

    console.log("Deploying InitSystem");
    system = new InitSystem(world, address(components));
    world.registerSystem(address(system), InitSystemID);
    authorizeWriter(components, IndexerComponentID, address(system));
    authorizeWriter(components, PositionComponentID, address(system));
    console.log(address(system));

    console.log("Deploying PaintSystem");
    system = new PaintSystem(world, address(components));
    world.registerSystem(address(system), PaintSystemID);
    authorizeWriter(components, PositionComponentID, address(system));
    authorizeWriter(components, ColorComponentID, address(system));
    console.log(address(system));

    console.log("Deploying PaintRectSystem");
    system = new PaintRectSystem(world, address(components));
    world.registerSystem(address(system), PaintRectSystemID);
    authorizeWriter(components, ColorComponentID, address(system));
    console.log(address(system));
  }
}